version: '3.8'

services:
  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - POSTGRES_URL=postgresql://postgres:1sampai8@192.168.1.10/shopee
      - REDIS_URL=redis://redis:6379/0
      - SHOPEE_PARTNER_ID=your_partner_id
      - SHOPEE_PARTNER_KEY=your_partner_key
      - SHOPEE_SHOP_ID=your_shop_id

  # postgres:
  #   image: postgres:13
  #   container_name: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 1sampai8
  #     POSTGRES_DB: shopee
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"

volumes:
  postgres-data:
